[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi-color-codec = { path = "../lib", version = "0.8" }
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"

[lints]
workspace = true